kind = "mobile"
previewPath = "/luxe-mobile/"
title = "LUXE Mobile"
version = "1.0.0"
id = "artifacts/luxe-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/luxe-mobile/" ]
localPort = 23118

[services.development]
run = "pnpm --filter @workspace/luxe-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/luxe-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/luxe-mobile", "run", "serve" ]

[services.env]
PORT = "23118"
BASE_PATH = "/luxe-mobile/"
