// Auto-curated YouTube how-to demo video ids, keyed by exercise name.
// Sourced via YouTube search + oEmbed embeddability verification (no API key).
// Each id is embedded in an in-app privacy-friendly (youtube-nocookie) player;
// the UI falls back to a YouTube search link when an id is missing or a video is pulled.
// To refresh, re-run the curation and replace the ids below.
export const EXERCISE_VIDEO_IDS: Record<string, string> = {
  "Push-Up": "WDIpL0pjun0",
  "Incline Push-Up": "NEdo_I3OuVk",
  "Dumbbell Bench Press": "1V3vpcaxRYQ",
  "Incline Dumbbell Press": "a5mETInM9MU",
  "Dumbbell Chest Fly": "vJh-4hRLH-o",
  "Barbell Bench Press": "lWFknlOTbyM",
  "Machine Chest Press": "YXjhMV7uz4c",
  "Cable Chest Fly": "FkEwrtyb4sc",
  "Band Chest Press": "EIL8h0cgj2c",
  "Pull-Up": "l6-aIZTbAR0",
  "Chin-Up": "gibW62a_3o0",
  "Lat Pulldown": "8d6d46pGdQM",
  "One-Arm Dumbbell Row": "qN54-QNO1eQ",
  "Barbell Bent-Over Row": "qXrTDQG1oUQ",
  "Seated Cable Row": "vwHG9Jfu4sw",
  "Band Row": "hqFwwv6dFGY",
  "Machine Row": "FTwvmczf7bE",
  "Inverted Row": "GdyhjXlxE-U",
  "Straight-Arm Pulldown": "eKJUJ2eFPUY",
  "Back Extension": "8PtNY5luX8w",
  "Superman Hold": "ZYCLnrQGUls",
  "Romanian Deadlift": "3VXmecChYYM",
  "Dumbbell Romanian Deadlift": "fW8-0VV13w4",
  "Barbell Deadlift": "ZaTM37cfiDs",
  "Dumbbell Shrug": "8L6zjxBwVzM",
  "Barbell Shrug": "MlqHEfydPpE",
  "Face Pull": "pB9qVPwWp1I",
  "Band Face Pull": "OIMUU2Q-upU",
  "Dumbbell Shoulder Press": "E9ShwbwZ1zw",
  "Barbell Overhead Press": "nNMR9fRGRjQ",
  "Dumbbell Lateral Raise": "lnVEvYCBGDo",
  "Dumbbell Front Raise": "CH9JzDStL3U",
  "Rear Delt Fly": "LsT-bR_zxLo",
  "Machine Shoulder Press": "Gkk-6q7Rq-s",
  "Cable Lateral Raise": "lMJUXEvcMkQ",
  "Band Shoulder Press": "DWw4e2o9gto",
  "Pike Push-Up": "D_Ed8Ltoomc",
  "Dumbbell Bicep Curl": "iui51E31sX8",
  "Hammer Curl": "6fcemy1cjkI",
  "Barbell Curl": "N6paU6TGFWU",
  "Cable Curl": "4XQLqBelbPw",
  "Band Curl": "LLrNuMHjBsE",
  "Concentration Curl": "os52QEIXQtM",
  "Triceps Dip (Bench)": "7teVbX4DACw",
  "Overhead Dumbbell Triceps Extension": "AYqg9S5FrUU",
  "Cable Triceps Pushdown": "XpeCPOHJTK8",
  "Dumbbell Skull Crusher": "HurmGkvE5s0",
  "Band Triceps Pushdown": "jWMXsd8Mu3Y",
  "Close-Grip Push-Up": "CZT3gEobyOo",
  "Wrist Curl": "xeUGvGZzBG8",
  "Farmer's Carry": "uLkDyV12ky0",
  "Dead Hang": "dOCQjaasbGs",
  "Plank": "6LqqeBtFn9M",
  "Side Plank": "NQsqPcarPXY",
  "Dead Bug": "Aoipu_fl3HA",
  "Bird Dog": "_1j_HWknGLg",
  "Crunch": "okqQVQireEo",
  "Bicycle Crunch": "NWzlS1Lp1e8",
  "Mountain Climber": "ZhiCSdOVJp0",
  "Russian Twist": "_d5cpAre7_w",
  "Hanging Knee Raise": "Fl8rJJ7mZJM",
  "Cable Woodchopper": "suSEgI6VpBg",
  "Ab Wheel Rollout": "hZnLxitN1Hw",
  "Kettlebell Around the World": "HdoKWN4VQoQ",
  "Bodyweight Squat": "n_xLyzPEX7A",
  "Goblet Squat": "lRYBbchqxtI",
  "Barbell Back Squat": "sX_lHLorm38",
  "Walking Lunge": "DlhojghkaQ0",
  "Dumbbell Lunge": "TwEH620Pn6A",
  "Split Squat": "hYNhUFqT0IM",
  "Bulgarian Split Squat": "SkNsa3eBwLA",
  "Leg Press": "nDh_BlnLCGc",
  "Leg Extension": "9icS_gPceJQ",
  "Step-Up": "dc1oeS7YS6o",
  "Wall Sit": "gn1GW7dBoog",
  "Lying Leg Curl": "-X2Oz6h-1WI",
  "Glute-Ham Slider Curl": "0aRUs9loLnk",
  "Kettlebell Swing": "aSYap2yhW8s",
  "Single-Leg Romanian Deadlift": "wHktyQBgejo",
  "Band Leg Curl": "UAod62tMmhk",
  "Good Morning": "f23vXjoG2e8",
  "Glute Bridge": "OUgsJ8-Vi0E",
  "Dumbbell Hip Thrust": "fv6EfDZ0E28",
  "Barbell Hip Thrust": "W86oVlnLqY4",
  "Cable Kickback": "n-cgsNePyFo",
  "Band Lateral Walk": "M5uxEQH5BUM",
  "Clamshell": "qJhOH9-2yDw",
  "Single-Leg Glute Bridge": "yFNjwkUNIao",
  "Standing Calf Raise": "n-5T_oYc1oU",
  "Dumbbell Calf Raise": "lyDp3tbx3qU",
  "Seated Calf Raise": "1cvpm--Y-4I",
  "Burpee": "6Qig8TKXpmI",
  "Dumbbell Thruster": "UipBcISeiGU",
  "Kettlebell Goblet Clean": "2LeAAtnSqU0",
  "Dumbbell Renegade Row": "qmZJhocQVlM",
  "Bear Crawl": "l8eRtgP7ZoY",
  "Kettlebell Deadlift": "hinonqqzatk",
  "Jump Squat": "A-cFYWvaHr0",
  "Dumbbell Clean and Press": "sZ4XMWn8bAU",
};
