type ExerciseSeed = {
  name: string;
  primaryMuscle: string;
  secondaryMuscles: string[];
  equipment: string;
  category: string;
  difficulty: string;
  instructions: string;
};

export const EXERCISE_LIBRARY: ExerciseSeed[] = [
  // ---- Chest ----
  { name: "Push-Up", primaryMuscle: "chest", secondaryMuscles: ["triceps", "shoulders", "core"], equipment: "bodyweight", category: "push", difficulty: "beginner", instructions: "Hands slightly wider than shoulders, body in a straight line. Lower your chest to just above the floor, then press back up without letting your hips sag." },
  { name: "Incline Push-Up", primaryMuscle: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: "bodyweight", category: "push", difficulty: "beginner", instructions: "Place hands on a bench or counter. Keeping your body straight, lower your chest to the edge and press back up. The higher the surface, the easier it is." },
  { name: "Dumbbell Bench Press", primaryMuscle: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: "dumbbell", category: "push", difficulty: "beginner", instructions: "Lie on a flat bench with a dumbbell in each hand at chest level. Press both up until arms are straight, then lower with control to the sides of your chest." },
  { name: "Incline Dumbbell Press", primaryMuscle: "chest", secondaryMuscles: ["shoulders", "triceps"], equipment: "dumbbell", category: "push", difficulty: "intermediate", instructions: "Set a bench to a 30-45 degree incline. Press the dumbbells from shoulder level to straight overhead of your upper chest, then lower slowly." },
  { name: "Dumbbell Chest Fly", primaryMuscle: "chest", secondaryMuscles: ["shoulders"], equipment: "dumbbell", category: "push", difficulty: "intermediate", instructions: "Lie on a bench with arms above your chest, slight bend in the elbows. Open your arms wide until you feel a stretch, then squeeze them back together." },
  { name: "Barbell Bench Press", primaryMuscle: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: "barbell", category: "push", difficulty: "intermediate", instructions: "Grip the bar slightly wider than shoulders. Lower it to mid-chest with elbows about 45 degrees from your body, then press back to full lockout." },
  { name: "Machine Chest Press", primaryMuscle: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: "machine", category: "push", difficulty: "beginner", instructions: "Adjust the seat so handles sit at chest height. Press the handles forward until arms are extended, then return with control." },
  { name: "Cable Chest Fly", primaryMuscle: "chest", secondaryMuscles: ["shoulders"], equipment: "cable", category: "push", difficulty: "intermediate", instructions: "Set pulleys at chest height, step forward with one foot. With a slight elbow bend, bring the handles together in front of your chest and squeeze." },
  { name: "Band Chest Press", primaryMuscle: "chest", secondaryMuscles: ["triceps", "shoulders"], equipment: "band", category: "push", difficulty: "beginner", instructions: "Anchor a band behind you at chest height. Press the handles forward until arms are straight, keeping your core braced." },

  // ---- Lats / Back ----
  { name: "Pull-Up", primaryMuscle: "lats", secondaryMuscles: ["biceps", "upper_back", "core"], equipment: "bodyweight", category: "pull", difficulty: "advanced", instructions: "Hang from a bar with an overhand grip. Pull your chin over the bar by driving your elbows down, then lower all the way with control." },
  { name: "Chin-Up", primaryMuscle: "lats", secondaryMuscles: ["biceps", "upper_back"], equipment: "bodyweight", category: "pull", difficulty: "intermediate", instructions: "Hang from a bar with palms facing you. Pull your chin over the bar, squeezing your lats and biceps, then lower slowly." },
  { name: "Lat Pulldown", primaryMuscle: "lats", secondaryMuscles: ["biceps", "upper_back"], equipment: "cable", category: "pull", difficulty: "beginner", instructions: "Grip the bar wider than shoulders. Pull it down to your upper chest while keeping your torso tall, then let it rise with control." },
  { name: "One-Arm Dumbbell Row", primaryMuscle: "lats", secondaryMuscles: ["upper_back", "biceps"], equipment: "dumbbell", category: "pull", difficulty: "beginner", instructions: "Place one hand and knee on a bench, back flat. Row the dumbbell to your hip, leading with the elbow, then lower fully." },
  { name: "Barbell Bent-Over Row", primaryMuscle: "upper_back", secondaryMuscles: ["lats", "biceps", "lower_back"], equipment: "barbell", category: "pull", difficulty: "intermediate", instructions: "Hinge at the hips with a flat back, bar hanging at arm's length. Row the bar to your lower ribs, then lower under control." },
  { name: "Seated Cable Row", primaryMuscle: "upper_back", secondaryMuscles: ["lats", "biceps"], equipment: "cable", category: "pull", difficulty: "beginner", instructions: "Sit tall with knees slightly bent. Pull the handle to your stomach, squeezing your shoulder blades together, then extend your arms fully." },
  { name: "Band Row", primaryMuscle: "upper_back", secondaryMuscles: ["lats", "biceps"], equipment: "band", category: "pull", difficulty: "beginner", instructions: "Anchor a band at chest height or loop it around your feet. Pull the handles to your ribs, squeezing your shoulder blades, then release slowly." },
  { name: "Machine Row", primaryMuscle: "upper_back", secondaryMuscles: ["lats", "biceps"], equipment: "machine", category: "pull", difficulty: "beginner", instructions: "Chest against the pad, grab the handles. Pull toward your torso, squeezing your mid-back, then return with control." },
  { name: "Inverted Row", primaryMuscle: "upper_back", secondaryMuscles: ["lats", "biceps", "core"], equipment: "bodyweight", category: "pull", difficulty: "intermediate", instructions: "Hang under a sturdy bar or table edge with your body straight. Pull your chest to the bar, then lower with control." },
  { name: "Straight-Arm Pulldown", primaryMuscle: "lats", secondaryMuscles: ["core"], equipment: "cable", category: "pull", difficulty: "intermediate", instructions: "With arms nearly straight, pull the bar from eye level down to your thighs in an arc, feeling your lats work. Return slowly." },

  // ---- Lower back ----
  { name: "Back Extension", primaryMuscle: "lower_back", secondaryMuscles: ["glutes", "hamstrings"], equipment: "bodyweight", category: "pull", difficulty: "beginner", instructions: "Lie face down or use a back extension bench. Lift your chest by squeezing your lower back and glutes, then lower slowly. Avoid overarching." },
  { name: "Superman Hold", primaryMuscle: "lower_back", secondaryMuscles: ["glutes", "upper_back"], equipment: "bodyweight", category: "core", difficulty: "beginner", instructions: "Lie face down, arms extended. Lift arms, chest, and legs off the floor at once, hold 2-3 seconds, then lower." },
  { name: "Romanian Deadlift", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "lower_back"], equipment: "barbell", category: "legs", difficulty: "intermediate", instructions: "Holding the bar at your thighs, push your hips back with a flat back until you feel a hamstring stretch, then drive your hips forward to stand." },
  { name: "Dumbbell Romanian Deadlift", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "lower_back"], equipment: "dumbbell", category: "legs", difficulty: "beginner", instructions: "Holding dumbbells in front of your thighs, hinge at the hips with a flat back until you feel a stretch, then stand tall by squeezing your glutes." },
  { name: "Barbell Deadlift", primaryMuscle: "lower_back", secondaryMuscles: ["glutes", "hamstrings", "traps", "forearms"], equipment: "barbell", category: "legs", difficulty: "advanced", instructions: "Stand with the bar over mid-foot. With a flat back, grip the bar and drive through your legs to stand tall, then lower it along your legs." },

  // ---- Traps ----
  { name: "Dumbbell Shrug", primaryMuscle: "traps", secondaryMuscles: ["forearms"], equipment: "dumbbell", category: "pull", difficulty: "beginner", instructions: "Hold dumbbells at your sides. Shrug your shoulders straight up toward your ears, pause, then lower slowly. Don't roll your shoulders." },
  { name: "Barbell Shrug", primaryMuscle: "traps", secondaryMuscles: ["forearms"], equipment: "barbell", category: "pull", difficulty: "beginner", instructions: "Hold the bar in front of your thighs. Shrug straight up, squeeze at the top, and lower under control." },
  { name: "Face Pull", primaryMuscle: "traps", secondaryMuscles: ["shoulders", "upper_back"], equipment: "cable", category: "pull", difficulty: "intermediate", instructions: "Set the rope at face height. Pull it toward your face, spreading the ends apart with elbows high, then return slowly. Great for posture." },
  { name: "Band Face Pull", primaryMuscle: "traps", secondaryMuscles: ["shoulders", "upper_back"], equipment: "band", category: "pull", difficulty: "beginner", instructions: "Anchor a band at face height. Pull it toward your eyes, spreading your hands apart and squeezing your rear shoulders." },

  // ---- Shoulders ----
  { name: "Dumbbell Shoulder Press", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], equipment: "dumbbell", category: "push", difficulty: "beginner", instructions: "Seated or standing with dumbbells at shoulder height, press them overhead until your arms are straight, then lower back to your shoulders." },
  { name: "Barbell Overhead Press", primaryMuscle: "shoulders", secondaryMuscles: ["triceps", "core"], equipment: "barbell", category: "push", difficulty: "intermediate", instructions: "With the bar at your collarbone, brace your core and press it straight overhead, finishing with the bar over mid-foot. Lower with control." },
  { name: "Dumbbell Lateral Raise", primaryMuscle: "shoulders", secondaryMuscles: [], equipment: "dumbbell", category: "push", difficulty: "beginner", instructions: "With a slight elbow bend, raise the dumbbells out to your sides until they reach shoulder height, then lower slowly. Use light weight." },
  { name: "Dumbbell Front Raise", primaryMuscle: "shoulders", secondaryMuscles: [], equipment: "dumbbell", category: "push", difficulty: "beginner", instructions: "Raise the dumbbells in front of you to shoulder height with straight-ish arms, then lower with control. Alternate arms or lift together." },
  { name: "Rear Delt Fly", primaryMuscle: "shoulders", secondaryMuscles: ["upper_back"], equipment: "dumbbell", category: "pull", difficulty: "beginner", instructions: "Hinge forward with a flat back, dumbbells hanging down. Raise them out to your sides, squeezing your rear shoulders, then lower slowly." },
  { name: "Machine Shoulder Press", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], equipment: "machine", category: "push", difficulty: "beginner", instructions: "Adjust the seat so handles are at shoulder height. Press up until arms are extended, then lower with control." },
  { name: "Cable Lateral Raise", primaryMuscle: "shoulders", secondaryMuscles: [], equipment: "cable", category: "push", difficulty: "intermediate", instructions: "Stand side-on to a low pulley. Raise the handle out to your side to shoulder height, keeping a slight elbow bend, then lower slowly." },
  { name: "Band Shoulder Press", primaryMuscle: "shoulders", secondaryMuscles: ["triceps"], equipment: "band", category: "push", difficulty: "beginner", instructions: "Stand on the band with handles at your shoulders. Press overhead until your arms are straight, then lower under control." },
  { name: "Pike Push-Up", primaryMuscle: "shoulders", secondaryMuscles: ["triceps", "core"], equipment: "bodyweight", category: "push", difficulty: "intermediate", instructions: "From a downward-dog position with hips high, bend your elbows to lower the top of your head toward the floor, then press back up." },

  // ---- Biceps ----
  { name: "Dumbbell Bicep Curl", primaryMuscle: "biceps", secondaryMuscles: ["forearms"], equipment: "dumbbell", category: "pull", difficulty: "beginner", instructions: "With palms facing forward, curl the dumbbells to your shoulders without swinging, then lower all the way down." },
  { name: "Hammer Curl", primaryMuscle: "biceps", secondaryMuscles: ["forearms"], equipment: "dumbbell", category: "pull", difficulty: "beginner", instructions: "Hold dumbbells with palms facing each other. Curl to your shoulders keeping the neutral grip, then lower with control." },
  { name: "Barbell Curl", primaryMuscle: "biceps", secondaryMuscles: ["forearms"], equipment: "barbell", category: "pull", difficulty: "beginner", instructions: "Grip the bar shoulder-width, palms up. Curl to your chest keeping elbows pinned at your sides, then lower slowly." },
  { name: "Cable Curl", primaryMuscle: "biceps", secondaryMuscles: ["forearms"], equipment: "cable", category: "pull", difficulty: "beginner", instructions: "Stand facing a low pulley. Curl the bar or handles to your shoulders with elbows at your sides, then lower under constant tension." },
  { name: "Band Curl", primaryMuscle: "biceps", secondaryMuscles: ["forearms"], equipment: "band", category: "pull", difficulty: "beginner", instructions: "Stand on the middle of the band. Curl the handles to your shoulders, keeping your elbows still, then lower slowly." },
  { name: "Concentration Curl", primaryMuscle: "biceps", secondaryMuscles: [], equipment: "dumbbell", category: "pull", difficulty: "beginner", instructions: "Seated, brace your elbow against your inner thigh. Curl the dumbbell to your shoulder slowly, squeezing at the top." },

  // ---- Triceps ----
  { name: "Triceps Dip (Bench)", primaryMuscle: "triceps", secondaryMuscles: ["chest", "shoulders"], equipment: "bodyweight", category: "push", difficulty: "beginner", instructions: "Hands on a bench behind you, legs extended forward. Bend your elbows to lower your hips, then press back up until arms are straight." },
  { name: "Overhead Dumbbell Triceps Extension", primaryMuscle: "triceps", secondaryMuscles: [], equipment: "dumbbell", category: "push", difficulty: "beginner", instructions: "Hold one dumbbell with both hands overhead. Bend your elbows to lower it behind your head, then extend back to straight arms." },
  { name: "Cable Triceps Pushdown", primaryMuscle: "triceps", secondaryMuscles: [], equipment: "cable", category: "push", difficulty: "beginner", instructions: "Elbows pinned at your sides, push the bar or rope down until your arms are fully straight, then let it rise with control." },
  { name: "Dumbbell Skull Crusher", primaryMuscle: "triceps", secondaryMuscles: [], equipment: "dumbbell", category: "push", difficulty: "intermediate", instructions: "Lying on a bench with arms straight up, bend only your elbows to lower the dumbbells beside your head, then extend back up." },
  { name: "Band Triceps Pushdown", primaryMuscle: "triceps", secondaryMuscles: [], equipment: "band", category: "push", difficulty: "beginner", instructions: "Anchor a band overhead. With elbows at your sides, push the band down until your arms are straight, then release slowly." },
  { name: "Close-Grip Push-Up", primaryMuscle: "triceps", secondaryMuscles: ["chest", "shoulders", "core"], equipment: "bodyweight", category: "push", difficulty: "intermediate", instructions: "Push-up with hands directly under your shoulders, elbows brushing your ribs as you lower. Press back up keeping your body straight." },

  // ---- Forearms ----
  { name: "Wrist Curl", primaryMuscle: "forearms", secondaryMuscles: [], equipment: "dumbbell", category: "pull", difficulty: "beginner", instructions: "Forearms resting on your thighs, palms up. Curl the dumbbells using only your wrists, then lower slowly." },
  { name: "Farmer's Carry", primaryMuscle: "forearms", secondaryMuscles: ["traps", "core"], equipment: "dumbbell", category: "full_body", difficulty: "beginner", instructions: "Hold heavy dumbbells at your sides and walk tall for 30-60 seconds, shoulders back and core braced." },
  { name: "Dead Hang", primaryMuscle: "forearms", secondaryMuscles: ["lats", "shoulders"], equipment: "bodyweight", category: "pull", difficulty: "beginner", instructions: "Hang from a bar with straight arms as long as you can, keeping your shoulders slightly engaged rather than fully relaxed." },

  // ---- Core ----
  { name: "Plank", primaryMuscle: "core", secondaryMuscles: ["shoulders", "glutes"], equipment: "bodyweight", category: "core", difficulty: "beginner", instructions: "Forearms on the floor, body in a straight line from head to heels. Brace your abs and hold without letting your hips sag or pike." },
  { name: "Side Plank", primaryMuscle: "core", secondaryMuscles: ["shoulders", "glutes"], equipment: "bodyweight", category: "core", difficulty: "beginner", instructions: "On one forearm, stack your feet and lift your hips so your body forms a straight line. Hold, then switch sides." },
  { name: "Dead Bug", primaryMuscle: "core", secondaryMuscles: [], equipment: "bodyweight", category: "core", difficulty: "beginner", instructions: "On your back with arms up and knees bent 90 degrees, slowly lower opposite arm and leg toward the floor, keeping your lower back pressed down." },
  { name: "Bird Dog", primaryMuscle: "core", secondaryMuscles: ["lower_back", "glutes"], equipment: "bodyweight", category: "core", difficulty: "beginner", instructions: "On hands and knees, extend opposite arm and leg until level with your torso, pause, and return. Keep your hips square." },
  { name: "Crunch", primaryMuscle: "core", secondaryMuscles: [], equipment: "bodyweight", category: "core", difficulty: "beginner", instructions: "Lying with knees bent, curl your shoulder blades off the floor by squeezing your abs, then lower slowly. Don't pull on your neck." },
  { name: "Bicycle Crunch", primaryMuscle: "core", secondaryMuscles: [], equipment: "bodyweight", category: "core", difficulty: "beginner", instructions: "Alternate bringing opposite elbow toward opposite knee while extending the other leg, rotating through your torso with control." },
  { name: "Mountain Climber", primaryMuscle: "core", secondaryMuscles: ["shoulders", "quads"], equipment: "bodyweight", category: "core", difficulty: "beginner", instructions: "From a push-up position, drive your knees toward your chest one at a time at a steady pace, keeping your hips level." },
  { name: "Russian Twist", primaryMuscle: "core", secondaryMuscles: [], equipment: "dumbbell", category: "core", difficulty: "intermediate", instructions: "Seated, lean back slightly with heels lightly touching or off the floor. Rotate a dumbbell side to side, turning from your torso." },
  { name: "Hanging Knee Raise", primaryMuscle: "core", secondaryMuscles: ["forearms"], equipment: "bodyweight", category: "core", difficulty: "intermediate", instructions: "Hanging from a bar, raise your knees toward your chest with control, then lower without swinging." },
  { name: "Cable Woodchopper", primaryMuscle: "core", secondaryMuscles: ["shoulders"], equipment: "cable", category: "core", difficulty: "intermediate", instructions: "Set the pulley high. Pull the handle diagonally across your body from high to low, rotating your torso, then return with control." },
  { name: "Ab Wheel Rollout", primaryMuscle: "core", secondaryMuscles: ["lats", "shoulders"], equipment: "bodyweight", category: "core", difficulty: "advanced", instructions: "Kneeling with hands on the wheel, roll forward as far as you can while keeping your back flat, then pull back using your abs." },
  { name: "Kettlebell Around the World", primaryMuscle: "core", secondaryMuscles: ["shoulders", "forearms"], equipment: "kettlebell", category: "core", difficulty: "beginner", instructions: "Pass the kettlebell around your body in a circle at hip height, bracing your core to stay still. Alternate directions." },

  // ---- Quads ----
  { name: "Bodyweight Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes", "hamstrings", "core"], equipment: "bodyweight", category: "legs", difficulty: "beginner", instructions: "Feet shoulder-width, sit your hips back and down until thighs are near parallel, keeping your chest up, then drive back to standing." },
  { name: "Goblet Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes", "core"], equipment: "dumbbell", category: "legs", difficulty: "beginner", instructions: "Hold a dumbbell vertically at your chest. Squat down keeping your elbows inside your knees and chest tall, then stand back up." },
  { name: "Barbell Back Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes", "hamstrings", "core", "lower_back"], equipment: "barbell", category: "legs", difficulty: "intermediate", instructions: "Bar on your upper back, feet shoulder-width. Squat until thighs are near parallel, keeping your chest up and knees tracking your toes." },
  { name: "Walking Lunge", primaryMuscle: "quads", secondaryMuscles: ["glutes", "hamstrings", "core"], equipment: "bodyweight", category: "legs", difficulty: "beginner", instructions: "Step forward and lower your back knee toward the floor, then push through the front heel to step into the next lunge." },
  { name: "Dumbbell Lunge", primaryMuscle: "quads", secondaryMuscles: ["glutes", "hamstrings"], equipment: "dumbbell", category: "legs", difficulty: "intermediate", instructions: "Holding dumbbells at your sides, step forward into a lunge until both knees are at 90 degrees, then push back to standing." },
  { name: "Split Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes", "hamstrings"], equipment: "bodyweight", category: "legs", difficulty: "beginner", instructions: "In a staggered stance, lower your back knee straight down until the front thigh is near parallel, then press back up. Finish one side, then switch." },
  { name: "Bulgarian Split Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes", "hamstrings", "core"], equipment: "dumbbell", category: "legs", difficulty: "advanced", instructions: "Rear foot elevated on a bench, dumbbells at your sides. Lower your back knee toward the floor, then drive up through your front heel." },
  { name: "Leg Press", primaryMuscle: "quads", secondaryMuscles: ["glutes", "hamstrings"], equipment: "machine", category: "legs", difficulty: "beginner", instructions: "Feet shoulder-width on the platform. Lower the sled until your knees reach about 90 degrees, then press back up without locking out hard." },
  { name: "Leg Extension", primaryMuscle: "quads", secondaryMuscles: [], equipment: "machine", category: "legs", difficulty: "beginner", instructions: "Seated with shins behind the pad, extend your knees until your legs are straight, squeeze, then lower with control." },
  { name: "Step-Up", primaryMuscle: "quads", secondaryMuscles: ["glutes", "hamstrings"], equipment: "dumbbell", category: "legs", difficulty: "beginner", instructions: "Holding dumbbells, step onto a sturdy bench or box, driving through the top heel to stand fully, then lower with control." },
  { name: "Wall Sit", primaryMuscle: "quads", secondaryMuscles: ["glutes", "core"], equipment: "bodyweight", category: "legs", difficulty: "beginner", instructions: "Slide down a wall until your thighs are parallel to the floor, knees at 90 degrees. Hold while breathing steadily." },

  // ---- Hamstrings ----
  { name: "Lying Leg Curl", primaryMuscle: "hamstrings", secondaryMuscles: ["calves"], equipment: "machine", category: "legs", difficulty: "beginner", instructions: "Face down with the pad above your heels. Curl your heels toward your glutes, squeeze, then lower slowly." },
  { name: "Glute-Ham Slider Curl", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "core"], equipment: "bodyweight", category: "legs", difficulty: "advanced", instructions: "On your back with heels on sliders or a towel, bridge your hips up and curl your heels toward you, then extend back out slowly." },
  { name: "Kettlebell Swing", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "core", "shoulders"], equipment: "kettlebell", category: "full_body", difficulty: "intermediate", instructions: "Hinge at the hips and swing the kettlebell between your legs, then snap your hips forward to float it to chest height. The power comes from your hips, not your arms." },
  { name: "Single-Leg Romanian Deadlift", primaryMuscle: "hamstrings", secondaryMuscles: ["glutes", "core", "lower_back"], equipment: "dumbbell", category: "legs", difficulty: "intermediate", instructions: "Balancing on one leg with a dumbbell in the opposite hand, hinge forward with a flat back as your rear leg lifts, then return to standing." },
  { name: "Band Leg Curl", primaryMuscle: "hamstrings", secondaryMuscles: [], equipment: "band", category: "legs", difficulty: "beginner", instructions: "Anchor a band low behind you and loop it around one ankle. Curl your heel toward your glutes, then release slowly." },
  { name: "Good Morning", primaryMuscle: "hamstrings", secondaryMuscles: ["lower_back", "glutes"], equipment: "barbell", category: "legs", difficulty: "advanced", instructions: "With a light bar on your upper back, hinge at the hips with a flat back until your torso nears parallel, then stand tall. Keep it light." },

  // ---- Glutes ----
  { name: "Glute Bridge", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings", "core"], equipment: "bodyweight", category: "legs", difficulty: "beginner", instructions: "On your back with knees bent, drive through your heels to lift your hips until your body is straight from knees to shoulders. Squeeze at the top." },
  { name: "Dumbbell Hip Thrust", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings", "core"], equipment: "dumbbell", category: "legs", difficulty: "intermediate", instructions: "Upper back on a bench, dumbbell across your hips. Drive your hips up until your torso is level, squeeze your glutes hard, then lower." },
  { name: "Barbell Hip Thrust", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings", "core"], equipment: "barbell", category: "legs", difficulty: "intermediate", instructions: "Upper back on a bench with a padded bar over your hips. Drive your hips to full extension, pause, then lower with control." },
  { name: "Cable Kickback", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings"], equipment: "cable", category: "legs", difficulty: "beginner", instructions: "With an ankle strap on a low pulley, kick one leg straight back, squeezing your glute, then return with control." },
  { name: "Band Lateral Walk", primaryMuscle: "glutes", secondaryMuscles: ["quads"], equipment: "band", category: "legs", difficulty: "beginner", instructions: "Loop a band above your knees, sit into a quarter squat, and step sideways keeping tension on the band. Walk both directions." },
  { name: "Clamshell", primaryMuscle: "glutes", secondaryMuscles: [], equipment: "band", category: "legs", difficulty: "beginner", instructions: "Lying on your side with knees bent and a band above your knees, open your top knee like a clamshell while keeping your feet together." },
  { name: "Single-Leg Glute Bridge", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings", "core"], equipment: "bodyweight", category: "legs", difficulty: "intermediate", instructions: "Set up like a glute bridge but extend one leg. Drive through the planted heel to lift your hips level, then lower. Switch sides." },

  // ---- Calves ----
  { name: "Standing Calf Raise", primaryMuscle: "calves", secondaryMuscles: [], equipment: "bodyweight", category: "legs", difficulty: "beginner", instructions: "Rise onto the balls of your feet as high as possible, pause at the top, then lower your heels slowly. Do it on a step for extra range." },
  { name: "Dumbbell Calf Raise", primaryMuscle: "calves", secondaryMuscles: [], equipment: "dumbbell", category: "legs", difficulty: "beginner", instructions: "Holding dumbbells at your sides, rise onto the balls of your feet, pause, and lower slowly with control." },
  { name: "Seated Calf Raise", primaryMuscle: "calves", secondaryMuscles: [], equipment: "machine", category: "legs", difficulty: "beginner", instructions: "Seated with the pad on your thighs, raise your heels as high as possible, pause, then lower for a full stretch." },

  // ---- Full body / conditioning ----
  { name: "Burpee", primaryMuscle: "quads", secondaryMuscles: ["chest", "core", "shoulders"], equipment: "bodyweight", category: "full_body", difficulty: "intermediate", instructions: "From standing, drop into a push-up, jump your feet back to your hands, and jump up with arms overhead. Move at a steady pace." },
  { name: "Dumbbell Thruster", primaryMuscle: "quads", secondaryMuscles: ["shoulders", "glutes", "core"], equipment: "dumbbell", category: "full_body", difficulty: "intermediate", instructions: "Holding dumbbells at your shoulders, squat down, then drive up and press the weights overhead in one fluid motion." },
  { name: "Kettlebell Goblet Clean", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings", "biceps", "core"], equipment: "kettlebell", category: "full_body", difficulty: "intermediate", instructions: "Swing the kettlebell from between your legs and pull it smoothly to a goblet position at your chest, then lower and repeat." },
  { name: "Dumbbell Renegade Row", primaryMuscle: "upper_back", secondaryMuscles: ["core", "lats", "triceps"], equipment: "dumbbell", category: "full_body", difficulty: "advanced", instructions: "In a push-up position gripping dumbbells, row one weight to your ribs while bracing hard to keep your hips still. Alternate sides." },
  { name: "Bear Crawl", primaryMuscle: "core", secondaryMuscles: ["shoulders", "quads"], equipment: "bodyweight", category: "full_body", difficulty: "beginner", instructions: "On hands and toes with knees hovering just off the floor, crawl forward moving opposite hand and foot together. Keep your back flat." },
  { name: "Kettlebell Deadlift", primaryMuscle: "glutes", secondaryMuscles: ["hamstrings", "lower_back", "forearms"], equipment: "kettlebell", category: "legs", difficulty: "beginner", instructions: "With the kettlebell between your feet, hinge at the hips with a flat back, grip the handle, and stand tall by driving your hips forward." },
  { name: "Jump Squat", primaryMuscle: "quads", secondaryMuscles: ["glutes", "calves"], equipment: "bodyweight", category: "legs", difficulty: "intermediate", instructions: "Squat down and explode upward into a jump, landing softly with bent knees straight into the next rep." },
  { name: "Dumbbell Clean and Press", primaryMuscle: "shoulders", secondaryMuscles: ["glutes", "hamstrings", "core", "traps"], equipment: "dumbbell", category: "full_body", difficulty: "advanced", instructions: "From a hinge, pull the dumbbells to your shoulders in one motion, then press overhead. Lower and repeat with a braced core." },
];
