import { pgTable, serial, text, timestamp } from "drizzle-orm/pg-core";

/**
 * One-time membership access codes.
 * - kind "six_month": generated by staff or admin; redeeming grants 6 months of comp access.
 * - kind "unlimited": generated by admin only; redeeming grants lifetime comp access.
 * A code can be redeemed exactly once; revoking removes the redeemer's comp access.
 */
export const membershipCodesTable = pgTable("membership_codes", {
  id: serial("id").primaryKey(),
  code: text("code").notNull().unique(),
  kind: text("kind").notNull(), // "six_month" | "unlimited"
  createdBy: text("created_by").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  redeemedBy: text("redeemed_by"),
  redeemedAt: timestamp("redeemed_at", { withTimezone: true }),
  // For six_month codes: the date the free period ends (set at redemption, for review).
  accessUntil: timestamp("access_until", { withTimezone: true }),
  revokedAt: timestamp("revoked_at", { withTimezone: true }),
  revokedBy: text("revoked_by"),
});

export type MembershipCode = typeof membershipCodesTable.$inferSelect;

/**
 * One-time staff access codes (admin-generated, one per staff member).
 * Redeeming a code upgrades the redeemer's account to the "staff" role.
 * A code can be redeemed exactly once; unredeemed codes can be revoked.
 * Demoting an existing staff member is done via role management, not here.
 */
export const staffCodesTable = pgTable("staff_codes", {
  id: serial("id").primaryKey(),
  code: text("code").notNull().unique(),
  // Optional note for whom the code was made (e.g. the staff member's name).
  label: text("label"),
  createdBy: text("created_by").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  redeemedBy: text("redeemed_by"),
  redeemedAt: timestamp("redeemed_at", { withTimezone: true }),
  revokedAt: timestamp("revoked_at", { withTimezone: true }),
  revokedBy: text("revoked_by"),
});

export type StaffCode = typeof staffCodesTable.$inferSelect;
